# DigitalOcean App Platform spec
name: muta-orders-backend
region: nyc
services:
  - name: api
    dockerfile_path: apps/backend/Dockerfile
    source_dir: /
    github:
      branch: main
      deploy_on_push: true
      repo: jzambrano12/muta-technical-test
    http_port: 3001
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://muta-technical-test-frontend.vercel.app
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
